[project]
name = "johnslifelinehopefully"
version = "0.1.0"
description = ""
authors = [
    {name = "john dowling",email = "john.dowling@diskarchive.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests (>=2.34.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
