"""
execution/interface.py

Broker-agnostic execution interface. The decision engine talks only to
`BrokerInterface` — never to a specific broker's client directly. This
keeps the decision engine (TensorFlow model + policy) fully decoupled
from execution, per the project's core design goal.

Concrete implementations (e.g. Trading212Broker, PaperBroker,
BacktestBroker) live alongside this file and implement this contract.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from enum import Enum


class Side(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class TimeInForce(Enum):
    DAY = "DAY"
    GOOD_TILL_CANCEL = "GOOD_TILL_CANCEL"


@dataclass(frozen=True)
class Quote:
    """
    A point-in-time price for an instrument.

    bid/ask are Optional because not every broker exposes them (Trading212's
    public API, for example, only gives a single last-traded-style price —
    see the interface spec doc). The policy layer must treat a missing
    spread as "unknown" rather than assuming it's zero.
    """
    ticker: str
    price: float
    bid: float | None
    ask: float | None
    currency: str
    as_of: datetime

    @property
    def spread(self) -> float | None:
        if self.bid is None or self.ask is None:
            return None
        return self.ask - self.bid

    @property
    def spread_pct(self) -> float | None:
        """Spread as a fraction of mid price, e.g. 0.001 == 0.1%."""
        spread = self.spread
        if spread is None or self.price == 0:
            return None
        return spread / self.price


@dataclass(frozen=True)
class Order:
    """A broker-agnostic order request."""
    ticker: str
    side: Side
    quantity: float
    order_type: OrderType
    limit_price: float | None = None
    stop_price: float | None = None
    time_in_force: TimeInForce = TimeInForce.DAY
    extended_hours: bool = False
    # Generated by the caller, not the broker — used for client-side
    # idempotency since some broker APIs (e.g. Trading212's, in beta)
    # don't guarantee it themselves.
    client_order_id: str | None = None

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError("quantity must be positive; direction is set via `side`")
        if self.order_type in (OrderType.LIMIT, OrderType.STOP_LIMIT) and self.limit_price is None:
            raise ValueError(f"{self.order_type} requires limit_price")
        if self.order_type in (OrderType.STOP, OrderType.STOP_LIMIT) and self.stop_price is None:
            raise ValueError(f"{self.order_type} requires stop_price")


class OrderStatus(Enum):
    PENDING = "PENDING"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


@dataclass(frozen=True)
class OrderResult:
    """What a broker hands back after an order is placed or queried."""
    broker_order_id: str
    status: OrderStatus
    filled_quantity: float
    filled_price: float | None
    # Fees/taxes actually charged, if known at this point (may be partial
    # or absent immediately after placement, and only complete once the
    # broker reports the fill — see cost model notes in the spec doc).
    fees: float | None = None


@dataclass(frozen=True)
class Position:
    ticker: str
    quantity: float
    average_price_paid: float
    current_price: float
    unrealised_pnl: float
    currency: str


@dataclass(frozen=True)
class AccountSnapshot:
    currency: str
    cash: float
    invested: float
    total_value: float
    as_of: datetime


class BrokerInterface(ABC):
    """
    The single boundary between the decision engine and the outside world.

    Every concrete broker (real, paper, or backtest) implements this same
    contract, so the decision engine can be pointed at any of them without
    changing a line of its own code.
    """

    @abstractmethod
    def get_quote(self, ticker: str) -> Quote:
        """Fetch the current price (and spread, where available) for ticker."""
        raise NotImplementedError

    @abstractmethod
    def place_order(self, order: Order) -> OrderResult:
        """Submit an order for execution."""
        raise NotImplementedError

    @abstractmethod
    def cancel_order(self, broker_order_id: str) -> None:
        """Attempt to cancel a pending order. Not guaranteed if already filling."""
        raise NotImplementedError

    @abstractmethod
    def get_order(self, broker_order_id: str) -> OrderResult:
        """Look up the current state of a previously placed order."""
        raise NotImplementedError

    @abstractmethod
    def get_positions(self) -> list[Position]:
        """All currently open positions."""
        raise NotImplementedError

    @abstractmethod
    def get_account(self) -> AccountSnapshot:
        """Cash, invested value, and total account value."""
        raise NotImplementedError